spring:
  security:
    filter:
      order: -100
    jwt:
      key: asdfaefasfe
      # 几小时后过期
      expire: 1
  datasource:
    url: jdbc:mysql://localhost:3306/bili-project
    username: root
    password: nuanyang
    driver-class-name: com.mysql.cj.jdbc.Driver
  mail:
    host: smtp.qq.com
    username: tony.nuanyang@qq.com
    password: hekgdniglsbxjgcj
    properties:
      mail:
        smtp:
          ssl:
            enable: true
  rabbitmq:
    addresses: localhost:5673
    username: admin
    password: admin
    virtual-host: /
  data:
    redis:
      host: localhost
      port: 16379
      password: admin
      database: 0
      # 连接超时
      connect-timeout: 5s
      # 读超时
      timeout: 5s
